/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.semsalario.poo2.view;

/**
 *
 * @author jp
 */
public class GUIAlt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIAlt.class.getName());

    /**
     * Creates new form GUIAlt
     */
    public GUIAlt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUIMain1 = new com.mycompany.semsalario.poo2.view.GUIMain();
        jLabel1 = new javax.swing.JLabel();
        jLabelRacAdmAdiPessoa = new javax.swing.JLabel();
        jTextFieldRacAdmQuemPagou = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRacAdm = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabelRacAdmValor = new javax.swing.JLabel();
        jTextFieldRacAdmValor = new javax.swing.JTextField();
        jLabelRacAdmTipo = new javax.swing.JLabel();
        jRadioButtonRacAdmEntrada = new javax.swing.JRadioButton();
        jRadioButtonRacAdmSaida = new javax.swing.JRadioButton();
        jButtonRacAdmInserir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRacAdmId = new javax.swing.JTextField();
        jButtonRacAdmAtualizar = new javax.swing.JButton();
        jButtonRacAdmDeletar = new javax.swing.JButton();
        jTextFieldRacAdmQualRacha = new javax.swing.JTextField();
        jButtonRacAdmLer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alt - Registros coletivo - churrasco sla das quantas");

        jLabelRacAdmAdiPessoa.setText("Quem pagou");

        jTableRacAdm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipo", "valor", "qual racha", "quem pagou", "id"
            }
        ));
        jScrollPane1.setViewportView(jTableRacAdm);

        jLabel3.setText("Qual racha");

        jLabelRacAdmValor.setText("Valor");

        jLabelRacAdmTipo.setText("Tipo");

        jRadioButtonRacAdmEntrada.setText("Entrada");
        jRadioButtonRacAdmEntrada.addActionListener(this::jRadioButtonRacAdmEntradaActionPerformed);

        jRadioButtonRacAdmSaida.setText("Saida");
        jRadioButtonRacAdmSaida.addActionListener(this::jRadioButtonRacAdmSaidaActionPerformed);

        jButtonRacAdmInserir.setText("inserir");
        jButtonRacAdmInserir.addActionListener(this::jButtonRacAdmInserirActionPerformed);

        jLabel2.setText("id");

        jTextFieldRacAdmId.addActionListener(this::jTextFieldRacAdmIdActionPerformed);

        jButtonRacAdmAtualizar.setText("editar");

        jButtonRacAdmDeletar.setText("excluir");
        jButtonRacAdmDeletar.addActionListener(this::jButtonRacAdmDeletarActionPerformed);

        jButtonRacAdmLer.setText("ler");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(446, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonRacAdmLer))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelRacAdmTipo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonRacAdmSaida)
                                                    .addComponent(jRadioButtonRacAdmEntrada)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButtonRacAdmInserir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelRacAdmValor)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldRacAdmValor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldRacAdmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonRacAdmAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonRacAdmDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRacAdmQualRacha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelRacAdmAdiPessoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldRacAdmQuemPagou, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelRacAdmTipo)
                                    .addComponent(jRadioButtonRacAdmEntrada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonRacAdmSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelRacAdmValor)
                                    .addComponent(jTextFieldRacAdmValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRacAdmInserir))
                            .addComponent(jButtonRacAdmLer)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldRacAdmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRacAdmAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRacAdmDeletar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldRacAdmQualRacha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRacAdmAdiPessoa)
                            .addComponent(jTextFieldRacAdmQuemPagou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRacAdmEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRacAdmEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRacAdmEntradaActionPerformed

    private void jRadioButtonRacAdmSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRacAdmSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRacAdmSaidaActionPerformed

    private void jTextFieldRacAdmIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRacAdmIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRacAdmIdActionPerformed

    private void jButtonRacAdmDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRacAdmDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRacAdmDeletarActionPerformed

    private void jButtonRacAdmInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRacAdmInserirActionPerformed
        /*String inputValor = jTextFieldRacAdmValor.getText();
        String tipo = "";
        
        float valor = Float.parseFloat(inputValor);
        
        if (jRadioButtonRacAdmEntrada.isSelected()) {
            tipo = "entrada";
        }
        else if (jRadioButtonRacAdmSaida.isSelected()) {
            tipo = "saida";
        }
        
        Registro registro = new Registro(tipo, valor);
        RegistroCtrl rCtrl = new RegistroCtrl();
        rCtrl.inserir(registro);
       
        System.out.println("registro inserido no sistema");
        jTextFieldRacAdmValor.setText("");
        buttonGroupRacAdmTipo.clearSelection();*/
    }//GEN-LAST:event_jButtonRacAdmInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIAlt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.semsalario.poo2.view.GUIMain gUIMain1;
    private javax.swing.JButton jButtonRacAdmAtualizar;
    private javax.swing.JButton jButtonRacAdmDeletar;
    private javax.swing.JButton jButtonRacAdmInserir;
    private javax.swing.JButton jButtonRacAdmLer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelRacAdmAdiPessoa;
    private javax.swing.JLabel jLabelRacAdmTipo;
    private javax.swing.JLabel jLabelRacAdmValor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButtonRacAdmEntrada;
    private javax.swing.JRadioButton jRadioButtonRacAdmSaida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRacAdm;
    private javax.swing.JTextField jTextFieldRacAdmId;
    private javax.swing.JTextField jTextFieldRacAdmQualRacha;
    private javax.swing.JTextField jTextFieldRacAdmQuemPagou;
    private javax.swing.JTextField jTextFieldRacAdmValor;
    // End of variables declaration//GEN-END:variables
}
