/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.semsalario.poo2.view;

/**
 *
 * @author jp
 */
public class GUICadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUICadastro.class.getName());

    /**
     * Creates new form GUICadastro
     */
    public GUICadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastro = new javax.swing.JLabel();
        jLabelCadastroEmail = new javax.swing.JLabel();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jLabelCadastroSenha = new javax.swing.JLabel();
        jTextFieldCadastroSenha = new javax.swing.JTextField();
        jLabelCadastroSenhaConfirma = new javax.swing.JLabel();
        jTextFieldCadastroSenhaConfirma = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jLabelLoginEmail = new javax.swing.JLabel();
        jTextFieldLoginEmail = new javax.swing.JTextField();
        jLabelLoginSenha = new javax.swing.JLabel();
        jTextFieldLoginSenha = new javax.swing.JTextField();
        jButtonCadastroLimpar = new javax.swing.JButton();
        jButtonCadastroCadastrar = new javax.swing.JButton();
        jButtonLoginLimpar = new javax.swing.JButton();
        jButtonLoginLogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCadastro.setText("Cadastro");

        jLabelCadastroEmail.setText("Email:");

        jLabelCadastroSenha.setText("Senha:");

        jTextFieldCadastroSenha.addActionListener(this::jTextFieldCadastroSenhaActionPerformed);

        jLabelCadastroSenhaConfirma.setText("Confirme a senha:");

        jLabelLogin.setText("Login");

        jLabelLoginEmail.setText("Email:");

        jTextFieldLoginEmail.addActionListener(this::jTextFieldLoginEmailActionPerformed);

        jLabelLoginSenha.setText("Senha:");

        jTextFieldLoginSenha.addActionListener(this::jTextFieldLoginSenhaActionPerformed);

        jButtonCadastroLimpar.setText("Limpar");
        jButtonCadastroLimpar.addActionListener(this::jButtonCadastroLimparActionPerformed);

        jButtonCadastroCadastrar.setText("Cadastrar");
        jButtonCadastroCadastrar.addActionListener(this::jButtonCadastroCadastrarActionPerformed);

        jButtonLoginLimpar.setText("Limpar");
        jButtonLoginLimpar.addActionListener(this::jButtonLoginLimparActionPerformed);

        jButtonLoginLogar.setText("Logar");
        jButtonLoginLogar.addActionListener(this::jButtonLoginLogarActionPerformed);

        jLabel1.setText("Sem Salário - Poo 2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelCadastroSenhaConfirma)
                                .addComponent(jLabelCadastroEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCadastroSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCadastro, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jButtonCadastroLimpar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCadastroSenha)
                                    .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldCadastroSenhaConfirma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCadastroCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLoginLimpar)
                                    .addComponent(jLabelLoginSenha))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLoginLogar)
                                    .addComponent(jTextFieldLoginSenha)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelLoginEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLogin, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(66, 66, 66)
                                .addComponent(jTextFieldLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastro)
                    .addComponent(jLabelLogin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroEmail)
                    .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoginEmail)
                    .addComponent(jTextFieldLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroSenha)
                    .addComponent(jTextFieldCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoginSenha)
                    .addComponent(jTextFieldLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroSenhaConfirma)
                    .addComponent(jTextFieldCadastroSenhaConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLoginLimpar)
                    .addComponent(jButtonLoginLogar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroCadastrar)
                    .addComponent(jButtonCadastroLimpar))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLimparActionPerformed
        jTextFieldCadastroEmail.setText("");
        jTextFieldCadastroSenha.setText("");
        jTextFieldCadastroSenhaConfirma.setText("");
    }//GEN-LAST:event_jButtonCadastroLimparActionPerformed

    private void jTextFieldCadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroSenhaActionPerformed

    private void jTextFieldLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginSenhaActionPerformed

    private void jTextFieldLoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginEmailActionPerformed

    private void jButtonCadastroCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCadastrarActionPerformed
        // TODO add your handling code here:
        String email = jTextFieldCadastroEmail.getText();
        String senha = jTextFieldCadastroSenha.getText();
        String senhaSenha = jTextFieldCadastroSenhaConfirma.getText();
        
        System.out.println(email + senha + senhaSenha);
    }//GEN-LAST:event_jButtonCadastroCadastrarActionPerformed

    private void jButtonLoginLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginLimparActionPerformed
        jTextFieldLoginEmail.setText("");
        jTextFieldLoginSenha.setText("");
    }//GEN-LAST:event_jButtonLoginLimparActionPerformed

    private void jButtonLoginLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginLogarActionPerformed
        String email = jTextFieldCadastroEmail.getText();
        String senha = jTextFieldCadastroEmail.getText();
        
        System.out.println(email + senha);
    }//GEN-LAST:event_jButtonLoginLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUICadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCadastrar;
    private javax.swing.JButton jButtonCadastroLimpar;
    private javax.swing.JButton jButtonLoginLimpar;
    private javax.swing.JButton jButtonLoginLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelCadastroEmail;
    private javax.swing.JLabel jLabelCadastroSenha;
    private javax.swing.JLabel jLabelCadastroSenhaConfirma;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoginEmail;
    private javax.swing.JLabel jLabelLoginSenha;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldCadastroSenha;
    private javax.swing.JTextField jTextFieldCadastroSenhaConfirma;
    private javax.swing.JTextField jTextFieldLoginEmail;
    private javax.swing.JTextField jTextFieldLoginSenha;
    // End of variables declaration//GEN-END:variables
}
