/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.semsalario.poo2.view;

/**
 *
 * @author jp
 */

import com.mycompany.semsalario.poo2.model.Registro;
import com.mycompany.semsalario.poo2.controller.RegistroCtrl;

public class GUIMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMain.class.getName());

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRegAdmTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegAdmInserir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonRegAdmEditar = new javax.swing.JButton();
        jButtonRegAdmExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelRegistrosAdminValue = new javax.swing.JLabel();
        jTextFieldRegAdmValor = new javax.swing.JTextField();
        jLabelRegistrosAdminType = new javax.swing.JLabel();
        jRadioButtonRegAdmEntrada = new javax.swing.JRadioButton();
        jRadioButtonRegAdmSaida = new javax.swing.JRadioButton();
        jLabelRegAdmNome = new javax.swing.JLabel();
        jLabelRegAdmDescricao = new javax.swing.JLabel();
        jLabelRegAdmId = new javax.swing.JLabel();
        jTextFieldRegAdmDescricao = new javax.swing.JTextField();
        jTextFieldRegAdmNome = new javax.swing.JTextField();
        jTextFieldRegAdmId = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registros Admin");

        jButtonRegAdmInserir.setText("inserir");
        jButtonRegAdmInserir.addActionListener(this::jButtonRegAdmInserirActionPerformed);

        jButton2.setText("ler");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButtonRegAdmEditar.setText("editar");

        jButtonRegAdmExcluir.setText("excluir");
        jButtonRegAdmExcluir.addActionListener(this::jButtonRegAdmExcluirActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelRegistrosAdminValue.setText("Valor");

        jTextFieldRegAdmValor.addActionListener(this::jTextFieldRegAdmValorActionPerformed);

        jLabelRegistrosAdminType.setText("Tipo");

        buttonGroupRegAdmTipo.add(jRadioButtonRegAdmEntrada);
        jRadioButtonRegAdmEntrada.setText("Entrada");

        buttonGroupRegAdmTipo.add(jRadioButtonRegAdmSaida);
        jRadioButtonRegAdmSaida.setText("Saída");
        jRadioButtonRegAdmSaida.addActionListener(this::jRadioButtonRegAdmSaidaActionPerformed);

        jLabelRegAdmNome.setText("nome");

        jLabelRegAdmDescricao.setText("descrição");

        jLabelRegAdmId.setText("id");

        jTextFieldRegAdmId.addActionListener(this::jTextFieldRegAdmIdActionPerformed);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRegistrosAdminValue)
                                            .addComponent(jLabelRegistrosAdminType))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonRegAdmSaida)
                                            .addComponent(jRadioButtonRegAdmEntrada)
                                            .addComponent(jTextFieldRegAdmValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonRegAdmEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonRegAdmExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jButtonRegAdmInserir))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRegAdmDescricao)
                            .addComponent(jLabelRegAdmNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRegAdmId, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRegAdmId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRegAdmNome)
                            .addComponent(jTextFieldRegAdmDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistrosAdminValue)
                    .addComponent(jTextFieldRegAdmValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegistrosAdminType)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonRegAdmEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonRegAdmSaida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegAdmInserir)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegAdmNome)
                    .addComponent(jTextFieldRegAdmNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegAdmDescricao)
                    .addComponent(jTextFieldRegAdmDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegAdmId)
                    .addComponent(jTextFieldRegAdmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegAdmEditar)
                    .addComponent(jButtonRegAdmExcluir))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRegAdmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegAdmExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegAdmExcluirActionPerformed

    private void jRadioButtonRegAdmSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRegAdmSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRegAdmSaidaActionPerformed

    private void jButtonRegAdmInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegAdmInserirActionPerformed
        String inputValor = jTextFieldRegAdmValor.getText();
        float valor = Float.parseFloat(inputValor);
        
        String tipo = "";
        if (jRadioButtonRegAdmEntrada.isSelected()) {
            tipo = "entrada";
        }
        else if (jRadioButtonRegAdmSaida.isSelected()) {
            tipo = "saida";
        }
        
        /*if (valor == "" || valor.typeOf() === String) {
            System.out.println("valor invalido");
            jTextFieldRegAdmValor.setText("");
            return;
        }*/
        
        Registro registro = new Registro(valor, tipo);
        RegistroCtrl rCtrl = new RegistroCtrl();
        rCtrl.inserir(registro);
       
        System.out.println("registro inserido no sistema");
        jTextFieldRegAdmValor.setText("");
        buttonGroupRegAdmTipo.clearSelection();
    }//GEN-LAST:event_jButtonRegAdmInserirActionPerformed

    private void jTextFieldRegAdmIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegAdmIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegAdmIdActionPerformed

    private void jTextFieldRegAdmValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegAdmValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegAdmValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRegAdmTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRegAdmEditar;
    private javax.swing.JButton jButtonRegAdmExcluir;
    private javax.swing.JButton jButtonRegAdmInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegAdmDescricao;
    private javax.swing.JLabel jLabelRegAdmId;
    private javax.swing.JLabel jLabelRegAdmNome;
    private javax.swing.JLabel jLabelRegistrosAdminType;
    private javax.swing.JLabel jLabelRegistrosAdminValue;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButtonRegAdmEntrada;
    private javax.swing.JRadioButton jRadioButtonRegAdmSaida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldRegAdmDescricao;
    private javax.swing.JTextField jTextFieldRegAdmId;
    private javax.swing.JTextField jTextFieldRegAdmNome;
    private javax.swing.JTextField jTextFieldRegAdmValor;
    // End of variables declaration//GEN-END:variables
}
